-- Create panel users
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwabc', 'saad@gmail.com', 'Saad Sayyed', 'saad.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwxyz', 'ayman@gmail.com', 'Ayman Sayed', 'ayman.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerc', 'faraz@gmail.com', 'Faraz Pathan', 'faraz.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwera', 'amaan@gmail.com', 'Amaan Shaikh', 'amaan.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerg', 'khushi@gmail.com', 'Khushi Jethmalani', 'khushi.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerf', 'apoorvi@gmail.com', 'Apoorvi Jethmalani', 'apoorvi.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerh', 'zoya@gmail.com', 'Zoya Khan', 'zoya.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xweri', 'sahil@gmail.com', 'Sahil Shaikh', 'sahil.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerj', 'mehak@gmail.com', 'Mehak Sharma', 'mehak.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerk', 'neha@gmail.com', 'Neha Patel', 'neha.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerl', 'ravi@gmail.com', 'Ravi Desai', 'ravi.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerm', 'isha@gmail.com', 'Isha Nair', 'isha.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwern', 'tariq@gmail.com', 'Tariq Khan', 'tariq.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwero', 'ananya@gmail.com', 'Ananya Mehta', 'ananya.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerp', 'rohan@gmail.com', 'Rohan Verma', 'rohan.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerq', 'arjun@gmail.com', 'Arjun Malhotra', 'arjun.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwerr', 'sana@gmail.com', 'Sana Qureshi', 'sana.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwers', 'vikram@gmail.com', 'Vikram Singh', 'vikram.png', 'EMPLOYEE');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xwert', 'nisha@gmail.com', 'Nisha Iyer', 'nisha.png', 'ADMIN');
INSERT INTO panel_user VALUES ('user-1XghfgD2341Xweru', 'raj@gmail.com', 'Raj Kumar', 'raj.png', 'EMPLOYEE');

-- Delete panel users
DELETE FROM panel_user WHERE email = 'saad@gmail.com';
DELETE FROM panel_user WHERE email = 'ayman@gmail.com';
DELETE FROM panel_user WHERE email = 'faraz@gmail.com';
DELETE FROM panel_user WHERE email = 'amaan@gmail.com';
DELETE FROM panel_user WHERE email = 'khushi@gmail.com';
DELETE FROM panel_user WHERE email = 'apoorvi@gmail.com';
DELETE FROM panel_user WHERE email = 'zoya@gmail.com';
DELETE FROM panel_user WHERE email = 'sahil@gmail.com';
DELETE FROM panel_user WHERE email = 'mehak@gmail.com';
DELETE FROM panel_user WHERE email = 'neha@gmail.com';
DELETE FROM panel_user WHERE email = 'ravi@gmail.com';
DELETE FROM panel_user WHERE email = 'isha@gmail.com';
DELETE FROM panel_user WHERE email = 'tariq@gmail.com';
DELETE FROM panel_user WHERE email = 'ananya@gmail.com';
DELETE FROM panel_user WHERE email = 'rohan@gmail.com';
DELETE FROM panel_user WHERE email = 'arjun@gmail.com';
DELETE FROM panel_user WHERE email = 'sana@gmail.com';
DELETE FROM panel_user WHERE email = 'vikram@gmail.com';
DELETE FROM panel_user WHERE email = 'nisha@gmail.com';
DELETE FROM panel_user WHERE email = 'raj@gmail.com';